-- MySQL Script generated by MySQL Workbench
-- Sun 10 Dec 2023 02:35:27 PM EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB` ;

-- -----------------------------------------------------
-- Schema CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB` ;
USE `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB` ;

-- -----------------------------------------------------
-- Table `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Clients` ;

CREATE TABLE IF NOT EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Clients` (
  `ClientID` INT NOT NULL,
  `FIrstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Phone` INT(10) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ClientID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`EventExpenses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`EventExpenses` ;

CREATE TABLE IF NOT EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`EventExpenses` (
  `ExpenseID` INT NOT NULL,
  `EventID` INT NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Amount` DOUBLE NOT NULL,
  PRIMARY KEY (`ExpenseID`, `EventID`),
  INDEX `fk_Expenses_1_EventID_idx` (`EventID` ASC) VISIBLE,
  CONSTRAINT `fk_Expenses_1_EventID`
    FOREIGN KEY (`EventID`)
    REFERENCES `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Events` (`EventID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Events` ;

CREATE TABLE IF NOT EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Events` (
  `EventID` INT NOT NULL,
  `EventType` ENUM("TeamBuilding", "Wedding", "BachelorParty", "Conference") NOT NULL DEFAULT 'Wedding',
  `EventDate` DATE NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `ClientID` INT NOT NULL,
  PRIMARY KEY (`EventID`, `ClientID`),
  INDEX `fk_Events_1_ClientID_idx` (`ClientID` ASC) VISIBLE,
  CONSTRAINT `fk_Events_1_ClientID`
    FOREIGN KEY (`ClientID`)
    REFERENCES `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Clients` (`ClientID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`EventStaff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`EventStaff` ;

CREATE TABLE IF NOT EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`EventStaff` (
  `EventID` INT NOT NULL,
  `StaffID` INT(13) NOT NULL,
  PRIMARY KEY (`EventID`, `StaffID`),
  INDEX `fk_EventStaff_1_StaffID_idx` (`StaffID` ASC) VISIBLE,
  CONSTRAINT `fk_EventStaff_EventID`
    FOREIGN KEY (`EventID`)
    REFERENCES `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Events` (`EventID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EventStaff_1_StaffID`
    FOREIGN KEY (`StaffID`)
    REFERENCES `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Staff` (`CNP`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`EventSuppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`EventSuppliers` ;

CREATE TABLE IF NOT EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`EventSuppliers` (
  `EventSupplierID` INT NOT NULL,
  `EventID` INT NOT NULL,
  `SupplierID` INT NOT NULL,
  PRIMARY KEY (`EventSupplierID`, `EventID`, `SupplierID`),
  INDEX `fk_EventSuppliers_1_SupplierID_idx` (`SupplierID` ASC) VISIBLE,
  INDEX `fk_EventSuppliers_1_EventID_idx` (`EventID` ASC) VISIBLE,
  CONSTRAINT `fk_EventSuppliers_1_SupplierID`
    FOREIGN KEY (`SupplierID`)
    REFERENCES `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Suppliers` (`SupplierID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EventSuppliers_1_EventID`
    FOREIGN KEY (`EventID`)
    REFERENCES `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Events` (`EventID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Payments` ;

CREATE TABLE IF NOT EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Payments` (
  `PaymentID` INT NOT NULL,
  `EventID` INT NOT NULL,
  `Amount` DOUBLE NOT NULL,
  `PaymentDate` DATETIME NOT NULL,
  INDEX `fk_Payments_1_EventID_idx` (`EventID` ASC) VISIBLE,
  PRIMARY KEY (`PaymentID`, `EventID`),
  CONSTRAINT `fk_Payments_1_EventID`
    FOREIGN KEY (`EventID`)
    REFERENCES `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Events` (`EventID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Staff` ;

CREATE TABLE IF NOT EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Staff` (
  `CNP` INT(13) NOT NULL,
  `FIrstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Phone` INT(10) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CNP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Suppliers` ;

CREATE TABLE IF NOT EXISTS `CE_2_202_Litvinenco_Andrei_Alexandru_EventCompanyDB`.`Suppliers` (
  `SupplierID` INT NOT NULL,
  `SupplierName` VARCHAR(45) NOT NULL,
  `ServiceType` ENUM("Catering", "Filmography", "DJ", "Logistics", "Decorations", "Entertainment") NOT NULL DEFAULT 'Catering',
  `Phone` INT(110) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SupplierID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
